<a href="https://colab.research.google.com/github/KhamidjonovRakhmatullo/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [27]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy_vector_array:', arr) # 1D vector array

arr.shape # to know shape of array

numpy_vector_array: [1 3 5 7]


(4,)

In [28]:
matrix = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
print('numpy_matrix_array:', matrix) # 2D matrix array

matrix.shape  # to know shape of array

numpy_matrix_array: [[1 3 5 7]
 [2 4 6 8]]


(2, 4)

In [34]:
# dtype() -> to know type of data

a = np.array([1, 2, 3])
b = np.array([1.5, 2.3, 3.7])

print('type a:', a.dtype)
print('type b:', b.dtype)


type a: int64
type b: float64


In [31]:
# reshape() -> to reshape of data structure

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)

print("shaped_array:", b)
print("original_array:", a)


# Important:
# `reshape` qilayotganda elementlar soni mos bo‘lishi kerak.


shaped_array: [[1 2 3]
 [4 5 6]]
original_array: [1 2 3 4 5 6]


In [35]:
# astype() -> change data type

a = np.array([1, 2, 3])
b = a.astype(float)

print('float:', b)
print('original:', a)

float: [1. 2. 3.]
original: [1 2 3]


In [38]:
# np.zeros() -> faqat 0 lardan iborat array yaratadi
# np.ones() -> faqat 1 lardan iborat array yaratadi

zeros = np.zeros((2, 3))
ones = np.ones((2, 3))

print("zeros:", zeros)
print("ones:", ones)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
# ndim() -> array necha o‘lchamli ekanligini ko‘rsatadi

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)
# 2

# 1D -> oddiy array
# 2D -> matrix
# 3D -> ko‘p o‘lchamli array

2


In [44]:
# arange() -> berilgan oraliqda ketma-ket sonlardan array yaratadi

arr = np.arange(1, 6)
arr = np.arange(0, 10, 2)

print('arange:', arr)
print('arange with step:', arr)


arange: [0 2 4 6 8]
arange with step: [0 2 4 6 8]


In [46]:
# sum() -> array ichidagi barcha sonlarni qo‘shadi
# mean() -> array ichidagi sonlarning o‘rtacha qiymatini chiqaradi
# min() -> eng kichik qiymatni topadi
# max() -> eng katta qiymatni topadi

arr = np.array([1, 2, 3, 4])

print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())

10
2.5
1
4


In [48]:
# flatten() -> ko‘p o‘lchamli array’ni 1D array’ga aylantiradi

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

new_arr = matrix.flatten()

print(new_arr)
# [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [50]:
# T (Transpose) -> matrix’ning qator va ustunlarini almashtiradi

matrix = np.array([
    [1, 2],
    [3, 4]
])

new_matrix = matrix.T

print(new_matrix)


[[1 3]
 [2 4]]


In [57]:
# dot() -> ikki array/matrix orasida dot product hisoblaydi

a = np.array([
      [1, 2],
      [3, 4]
    ])

b = np.array([
      [4, 6],
      [7, 8]
    ])


print(a.dot(b))

# row from first matrix × column from second matrix
# calculation:
# [1, 2] × [4, 7] = 18
# [1, 2] × [6, 8] = 22
# [3, 4] × [4, 7] = 40
# [3, 4] × [6, 8] = 50

[[18 22]
 [40 50]]


In [61]:
# random.rand() -> 0 va 1 oralig‘ida random float sonlar yaratadi

arr = np.random.rand(2, 3)

print(arr)

[[0.34883492 0.22923817 0.91439796]
 [0.13117264 0.38920644 0.97047082]]
