<a href="https://colab.research.google.com/github/KhamidjonovRakhmatullo/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install pandas numpy

In [6]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("StudentsPerformance.csv")

print("\n==========================================\n")

print("Dataset shape (rows, columns):", df.shape)

print("\n==========================================\n")

print("Column name:", df.columns.tolist())

print("\n==========================================\n")

print("First 5 rows of the dataset:")
print(df.head())

print("\n==========================================\n")

print("Summary statistics:")
print(df.describe())

print("\n==========================================\n")

print("Data types and null info:")
print(df.info())

print("\n==========================================\n")



Dataset shape (rows, columns): (1000, 8)


Column name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']


First 5 rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             4

In [9]:
print("==========================================\n")

print("Avarage scores by subjects:")
df[["math score", "reading score", "writing score"]].mean()


Avarage scores by subjects:


,0
math score,66.089
reading score,69.169
writing score,68.054


In [10]:
print("==========================================\n")

print("Maximum scores by subjects:")
df[["math score", "reading score", "writing score"]].max()


Maximum scores by subjects:


,0
math score,100
reading score,100
writing score,100


In [11]:
print("==========================================\n")

print("Min scores by subjects:")
df[["math score", "reading score", "writing score"]].min()


Min scores by subjects:


,0
math score,0
reading score,17
writing score,10


In [12]:
# Correlation
print("==========================================\n")

print("Correlation:")
df[["math score", "reading score", "writing score"]].corr()


Correlation:


,math score,reading score,writing score
math score,1.000000,0.817580,0.802642
reading score,0.817580,1.000000,0.954598
writing score,0.802642,0.954598,1.000000


In [13]:
print("==========================================\n")

# total score -> math, reading, writing score'larni qo‘shadi
# axis=1 -> row bo‘yicha hisoblaydi, ya’ni har bir student uchun alohida qo‘shadi
df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1)


# average score -> total score'ni 3 ga bo‘lib, o‘rtacha ballni hisoblaydi
df["average score"] = df["total score"] / 3


# passed -> agar average score 50 yoki undan katta bo‘lsa "Yes", aks holda "No"
# np.where(condition, true_value, false_value)
df["passed"] = np.where(df["average score"] >= 50, "Yes", "No")


# faqat yangi yaratilgan column'larning birinchi 5 ta row'ini ko‘rsatadi
print(df[["total score", "average score", "passed"]].head())


   total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes


In [14]:
print("==========================================\n")

# Preparation-based average

# groupby() -> data'ni berilgan column bo‘yicha guruhlaydi
# bu yerda students "test preparation course" bo‘yicha guruhlanadi

test_prep_group = df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()

# "test preparation course" bo‘yicha:
# math score, reading score, writing score column'larining o‘rtacha qiymatini chiqaradi


print("student score by test preparation course: \n")
print(test_prep_group)
# result:
# completed -> test preparation course qilgan student'larning o‘rtacha ballari
# none      -> test preparation course qilmagan student'larning o‘rtacha ballari


print("==========================================\n")

# Gender-based average

gender_avg = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()

print("student score by gender: \n")
print(gender_avg)


print("==========================================\n")

# Passed vs Failed

# value_counts() -> "passed" column ichida Yes va No nechta ekanini sanaydi
# normalize=True -> son o‘rniga foiz/proportion qilib chiqaradi
# * 100 -> proportion'ni percentage'ga aylantiradi

pass_rate = df["passed"].value_counts(normalize=True) * 100


print("student pass rate: \n")

print(pass_rate)
# Yes -> passed student'lar foizi
# No  -> failed student'lar foizi


student score by test preparation course: 

                         math score  reading score  writing score
test preparation course                                          
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

student score by gender: 

        math score  reading score  writing score
gender                                          
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203

student pass rate: 

passed
Yes    89.7
No     10.3
Name: proportion, dtype: float64


In [20]:
print("==========================================\n")

print("Current score columns in data frame: \n")
print(df[["math score", "reading score", "writing score"]].head())


print("\n==========================================\n")


# Convert scores to NumPy array

scores = df[["math score", "reading score", "writing score"]].values
# Pandas DataFrame'dagi 3 ta score column'ni NumPy array/matrix ko‘rinishiga o‘tkazadi

print("\n NumPy Array Matrix:")
print(scores)


print("\n==========================================\n")


# Mean and Standard Deviation

mean_scores = np.mean(scores, axis=0)
# axis=0 -> har bir column bo‘yicha hamma 1000 row'larning mean hisoblaydi (average)
# math score mean, reading score mean, writing score mean

print("\nNumPy Mean: \n")
print(mean_scores)

print("\n---")

std_scores = np.std(scores, axis=0)
# axis=0 -> har bir column bo‘yicha hamma 1000 row'larning std hisoblaydi (bir-biriga qanchalik o'xshash(yaqin yoki uzoq) result'lar)
# har bir score column qanchalik tarqalganini ko‘rsatadi

print("\nNumPy Std: \n")
print(std_scores)


print("\n==========================================\n")


# Z-score / Normalization

z_score = (scores - mean_scores) / std_scores
# har bir score'dan o‘sha column mean'ini ayiradi
# keyin std'ga bo‘ladi
# natijada score'lar normalized bo‘ladi

print("\nZ-scores / Normalized numbers:\n")
print(z_score[:5])
# faqat birinchi 5 ta row'ni chiqaradi

# z-score around 0  -> average score'ga yaqin
# z-score negative  -> average'dan past
# z-score positive  -> average'dan yuqori



Current score columns in data frame: 

   math score  reading score  writing score
0          72             72             74
1          69             90             88
2          90             95             93
3          47             57             44
4          76             78             75



 NumPy Array Matrix:
[[72 72 74]
 [69 90 88]
 [90 95 93]
 ...
 [59 71 65]
 [68 78 77]
 [77 86 86]]



NumPy Mean: 

[66.089 69.169 68.054]

---

NumPy Std: 

[15.15549666 14.59289002 15.18805728]



Z-scores / Normalized numbers:

[[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]


In [28]:
# ------------------------------ Student performance check ------------------------------

# 1) How many students scored 90 or above average?

# average score 90 yoki undan yuqori bo‘lgan student'larni filter qiladi
top_scorers = df[df["average score"] >= 90]

print("Top scored students above 90:", len(top_scorers))


print("\n==========================================\n")


# 2) How many students failed?

# passed column'i "No" bo‘lgan student'larni filter qiladi
failed = df[df["passed"] == "No"]

print("Failed from exam:", len(failed))

Top scored students above 90: 52


Failed from exam: 103
